// Repository-specific inputs to the release scripts. The other scripts/*.mjs
// are verbatim copies of scshafe-dev's master (release/scripts/); change this
// file, not them. Generated by scshafe-dev v0.1.0, then filled in for
// @scshafe/ui.
export default {
  // Each directory in package.json `files` and what it may contain. src/ ships
  // the .tsx/.jsx component sources and one .js module beside the .ts ones.
  payload: { src: "\\.(?:ts|tsx|js|jsx)$", lib: "\\.(?:js|d\\.ts)$" },
  // Build output `pnpm run clean` removes; never committed (LIB-03).
  clean: ["lib"],
  // Packages the smokes need beside the peers (exact devDependencies): React
  // 19 ships no declarations, and the TypeScript smokes type React props.
  smokeExtraPackages: ["@types/react"],
  // The editor is optional (0.3.0): the base smokes prove the tiptap peers are
  // absent and @scshafe/ui/editor does not resolve, then the editor phase adds
  // them and runs test/smoke/editor/.
  phases: [
    {
      name: "editor",
      peers: [
        "@tiptap/core",
        "@tiptap/extension-link",
        "@tiptap/extension-placeholder",
        "@tiptap/pm",
        "@tiptap/react",
        "@tiptap/starter-kit",
        "tiptap-markdown"
      ]
    }
  ],
  // false: the TypeScript smoke also checks the peers' declarations.
  typeSmokeSkipLibCheck: false,
  // DOM as well: peers' declarations name AbortSignal and friends (the
  // switchyard-postgres and graphpaper smokes check them the same way).
  typeSmokeLib: ["ES2022", "DOM"]
};
